namespace NanaGet
{
    enum TaskStatus
    {
        Active,
        Waiting,
        Paused,
        Error,
        Complete,
        Removed
    };

    runtimeclass TaskItem : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Gid { get; };
        String Name { get; };
        Windows.Foundation.Uri Source{ get; };
        String Path { get; };
        TaskStatus Status { get; };
        UInt64 DownloadSpeed { get; };
        UInt64 UploadSpeed { get; };
        UInt64 BytesReceived { get; };
        UInt64 TotalBytesToReceive { get; };
        UInt64 RemainTime { get; };

        String StatusText{ get; };
    }

    [Windows.UI.Xaml.Data.Bindable]
    [Windows.Foundation.Metadata.WebHostHidden]
    runtimeclass TaskItemConverter :
        [default] Windows.UI.Xaml.Data.IValueConverter
    {
        TaskItemConverter();
    }
}
